### ISSUE TITLE
Status of this CLI / known bugs

### ISSUE THREAD

**Issue by zramsay** [cerc-io/laconic-registry-cli#17]
Queries by and large work (didn't test them all).

The only write/transaction I was able to make is `laconic cns bond create --type aphoton --quantity 1000000000 --gas 200000 --fees 200000aphoton` which worked and returned the bondID.

Publishing a record failed with the following error (second last line):
```
$ ./bin/laconic cns record publish --filename watcher.yml --bond-id c181cc901a0f020162846f77fa66a916bc0c064d0b423af0e2689974acbff3d1 --gas 200000 --fees 200000aphoton

github.com/cosmos/cosmos-sdk/x/auth/tx.DefaultTxDecoder.func1
	github.com/cosmos/cosmos-sdk@v0.46.7/x/auth/tx/decoder.go:42
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx
	github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/baseapp.go:660
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).CheckTx
	github.com/cosmos/cosmos-sdk@v0.46.7/baseapp/abci.go:244
github.com/tendermint/tendermint/abci/client.(*localClient).CheckTxAsync
	github.com/tendermint/tendermint@v0.34.24/abci/client/local_client.go:104
github.com/tendermint/tendermint/proxy.(*appConnMempool).CheckTxAsync
	github.com/tendermint/tendermint@v0.34.24/proxy/app_conn.go:126
github.com/tendermint/tendermint/mempool/v0.(*CListMempool).CheckTx
	github.com/tendermint/tendermint@v0.34.24/mempool/v0/clist_mempool.go:254
github.com/tendermint/tendermint/rpc/core.BroadcastTxCommit
	github.com/tendermint/tendermint@v0.34.24/rpc/core/mempool.go:91
github.com/tendermint/tendermint/rpc/client/local.(*Local).BroadcastTxCommit
	github.com/tendermint/tendermint@v0.34.24/rpc/client/local/local.go:91
github.com/cosmos/cosmos-sdk/client.Context.BroadcastTxCommit
	github.com/cosmos/cosmos-sdk@v0.46.7/client/broadcast.go:97
github.com/cosmos/cosmos-sdk/client.Context.BroadcastTx
	github.com/cosmos/cosmos-sdk@v0.46.7/client/broadcast.go:32
github.com/cosmos/cosmos-sdk/client.TxServiceBroadcast
	github.com/cosmos/cosmos-sdk@v0.46.7/client/broadcast.go:157
github.com/cosmos/cosmos-sdk/client.Context.Invoke
	github.com/cosmos/cosmos-sdk@v0.46.7/client/grpc_query.go:51
github.com/cosmos/cosmos-sdk/types/tx.(*serviceClient).BroadcastTx
	github.com/cosmos/cosmos-sdk@v0.46.7/types/tx/service.pb.go:855
github.com/cosmos/cosmos-sdk/types/tx.request_Service_BroadcastTx_0
	github.com/cosmos/cosmos-sdk@v0.46.7/types/tx/service.pb.gw.go:136
github.com/cosmos/cosmos-sdk/types/tx.RegisterServiceHandlerClient.func3
	github.com/cosmos/cosmos-sdk@v0.46.7/types/tx/service.pb.gw.go:477
github.com/grpc-ecosystem/grpc-gateway/runtime.(*ServeMux).ServeHTTP
	github.com/grpc-ecosystem/grpc-gateway@v1.16.0/runtime/mux.go:240
github.com/gorilla/mux.(*Router).ServeHTTP
	github.com/gorilla/mux@v1.8.0/mux.go:210
github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP
	github.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:256
github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1
	github.com/tendermint/tendermint@v0.34.24/rpc/jsonrpc/server/http_server.go:229
net/http.HandlerFunc.ServeHTTP
	net/http/server.go:2109
net/http.serverHandler.ServeHTTP
	net/http/server.go:2947
net/http.(*conn).serve
	net/http/server.go:1991
unable to resolve type URL /vulcanize.nameservice.v1beta1.MsgSetRecord: tx parse error
laconic cns record publish
```

We cut a new release of `laconic-sdk` to include what ideally would've been the fix ie., [this commit](https://github.com/cerc-io/laconic-sdk/commit/eaafeb910763677cd0ea360cd060a4a018cab59c)

and the error went from:
```
unable to resolve type URL /vulcanize.nameservice.v1beta1.MsgSetRecord: tx parse error
```
to
```
unable to resolve type URL : tx parse error
```

From discussion, it seems to be that a dependency went from using sha384 -> sha256 (or vice-versa?). The `laconic-sdk` and its tests were updated for that fix, but this CLI was not.

**Comment by 0xmuralik** [comment]
This might be using the old version of laconic-sdk repo. Fixed them in this PR https://github.com/cerc-io/laconic-sdk/pull/15.

**Comment by zramsay** [comment]
@0xmuralik the second error is using the [0.1.5 release](https://github.com/cerc-io/laconic-sdk/releases/tag/v0.1.5) cut yesterday so it included that PR. See the last line in my original comment:
> From discussion, it seems to be that a dependency went from using sha384 -> sha256 (or vice-versa?). The laconic-sdk and its tests were updated for that fix, but this CLI was not.

**Comment by i-norden** [comment]
Hey @zramsay stupid question: which version of laconicd are you running this against?

**Comment by 0xmuralik** [comment]
This error is due to change in record types support. We only support a few record types See: https://github.com/cerc-io/laconicd/issues/27, https://github.com/cerc-io/laconicd/issues/52 and https://github.com/cerc-io/laconicd/issues/51. 
You can get all the supported types from [here](https://github.com/cerc-io/laconicd/tree/murali/record-attributes/x/registry/helpers/examples).

**Comment by zramsay** [comment]
@0xmuralik thanks I will test out locally, however, if i understand correctly, it depends on https://github.com/cerc-io/laconicd/pull/79 and https://github.com/cerc-io/laconic-sdk/pull/27, can you confirm?

**Comment by 0xmuralik** [comment]
Hi @zramsay, the PRs you mentioned add support for additional record types. But with https://github.com/cerc-io/laconicd/pull/40 the support for the generic record type is removed and only the service provider and website registration records are supported.

**Comment by zramsay** [comment]
#23 and #24 seem to have solved my issues. #26 addresses updates to the README so that this works out of the box
