### ISSUE TITLE
Null auction in `laconic cns authority whois laconic`

### ISSUE THREAD

**Issue by i-norden** [cerc-io/laconic-registry-cli#18]
From Zach:

This works: `laconic cns authority reserve laconic`
but:
`laconic cns authority whois laconic` only provides a fraction of what was expected in the README

```
[
  {
    "ownerAddress": "ethm18ynlnm009ah5ck5vzjsl05m92qu2gql67ryklx",
    "ownerPublicKey": "AkfbHv+RjyTDre1nxcblPpVvimtZU4Q/uS8UiMPux/yo",
    "height": "40",
    "status": "active",
    "bondId": "",
    "expiryTime": "2023-01-15 19:09:12.737852 +0000 UTC",
    "auction": null
  }
]
```

vs

```
laconic cns authority whois laconic
[
  {
    "ownerAddress": "",
    "ownerPublicKey": "",
    "height": "183",
    "status": "expired",
    "bondId": "",
    "expiryTime": "2022-04-26 11:50:45.679728594 +0000 UTC",
    "auction": {
      "id": "0294fb2e3659c347b53a6faf4bef041fd934f0f3ab13df6d2468d5d63abacd48",
      "status": "commit",
      "ownerAddress": "ethm1lfekr7gvqtnhpp2kwdc6u2n569cqsp4ww0m4y8",
      "createTime": "2022-04-26T11:43:45.679728594",
      "commitsEndTime": "2022-04-26T11:44:45.679728594",
      "revealsEndTime": "2022-04-26T11:45:45.679728594",
      "commitFee": {
        "type": "aphoton",
        "quantity": "1000000"
      },
      "revealFee": {
        "type": "aphoton",
        "quantity": "1000000"
      },
      "minimumBid": {
        "type": "aphoton",
        "quantity": "5000000"
      },
      "winnerAddress": "",
      "winnerBid": {
        "type": "",
        "quantity": "0"
      },
      "winnerPrice": {
        "type": "",
        "quantity": "0"
      },
      "bids": []
    }
  }
]
```

The auction model is unexpectedly empty.

`laconic cns auction` only has two subcommands, `bid` and `get` so how do we create an auction?

**Comment by i-norden** [comment]
After speaking with @ABastionOfSanity and learning that the unit test that fails in https://github.com/cerc-io/laconic-sdk/issues/7 is getting back the CID of an empty JSON, I am starting to suspect this could be the same issue due to changes to the record types in laconicd that were not reflected here. The type mismatch causes the gRPC handler function to fail to decode the record (or in this case, a sub-record) and instead return empty JSON.

**Comment by ABastionOfSanity** [comment]
For clarification, the failing unit test mentioned above was getting back a incorrectly encoded CID, but not the CID for empty JSON.  Data over the wire was correct.

**Comment by 0xmuralik** [comment]
To create auction with reserveName the paramater registry.params.authority_auction_enabled must be true. This is false by default and set true only when we use `TEST_AUCTION_ENABLED=true ./init.sh` instead of `./init.sh` while starting the chain.

So to get auction with `laconic cns authority whois laconic` use `TEST_AUCTION_ENABLED=true ./init.sh` to start laconicd.
